### ISSUE TITLE
Stupid questions...

### ISSUE THREAD

**Issue by Paliscope** [koculu/ZoneTree#107] opened 2024-12-19 15:37 UTC
Hi!

Trying out Zonetree and the benchmarks seems very interesting.

I have some questions which I do think are on the stupid side...

I get it to start and I created a database of string, byte()
Seems to work, some files are created on the disk with a custom classifier

1. Trying to add 1.000.000 records but it fails when it comes to the 1.000.000 record (adding 999.999 works) Is there a setting for this?
2.It is creating files on the hard disk put no data is stored there. Is there a need to flush the data from memory to the disk?

In RocksDB, you have the options of Multiget, I have not seen anything similar here. Is it not needed (As for RocksDB it is needed to get some performance)

Allt the best!

**Comment by Paliscope** [comment] 2024-12-19 16:38
It is very basic. Just a first test:

This is the code


 public class Class1
 {
     public IZoneTree <string,byte[]> OpenDb(string dataPath)
     {
         using var zoneTree = new ZoneTreeFactory<string, byte[]>()
         .SetComparer(new StringOrdinalComparerAscending()) // Comparer for string keys
         .SetDataDirectory(dataPath)
         .SetKeySerializer(new Utf8StringSerializer()) // Serializer for string keys
         .SetValueSerializer(new CustomByteArraySerializer()) // Serializer for byte array values
         .OpenOrCreate();

         return zoneTree;
     }
 }

 public class CustomByteArraySerializer : ISerializer<byte[]>
 {
    

     public byte[] Deserialize(Memory<byte> bytes)
     {
         return bytes.ToArray();
     }

     public Memory<byte> Serialize(in byte[] entry)
     {
         return entry ?? Array.Empty<byte>();
     }
 }

Then I call from another project
and just add 1M items with 100 almost empty byte arrays with a key with a string of "Name" + index

**Comment by koculu** [comment] 2024-12-19 16:47
You said "it fails when it comes to the 1.000.000".
What exception do you get? How do you confirm that it fails?

**Comment by Paliscope** [comment] 2024-12-19 16:49
Here is the super simple VB.net program that uses the class above


when i reached 1000.000 in the loop I get this error:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

If I run to 999.999. it is  no problem




        Dim c As New ClassLibrary1.Class1
        Dim obj As Tenray.ZoneTree.Core.ZoneTree(Of String, Byte()) = c.OpenDb("data\testdb5")


        Dim Name As String = "name"
        Dim data As Byte()
        ReDim data(100) '
        data(5) = 10

        Dim watch As New Stopwatch
        watch.Start()

        Dim opindex As Long
        For i As Integer = 0 To 1000000
            obj.TryAtomicAdd("kalle" & i, data, opindex)
        Next

        watch.Stop()
        MsgBox(watch.ElapsedMilliseconds)

**Comment by koculu** [comment] 2024-12-19 16:57
Could you also share the stack trace information of the Error you get?

**Comment by Paliscope** [comment] 2024-12-19 16:58
at Tenray.ZoneTree.Core.ZoneTreeMetaWAL`2.AppendRecord(MetaWalRecord& record)
   at Tenray.ZoneTree.Core.ZoneTreeMetaWAL`2.EnqueueMaximumOpIndex(Int64 maximumOpIndex)
   at Tenray.ZoneTree.Core.ZoneTree`2.MoveMutableSegmentForward(IMutableSegment`2 mutableSegment)
   at Tenray.ZoneTree.Core.ZoneTree`2.Upsert(TKey& key, TValue& value)
   at TestZoneTree.Form1.Button1_Click(Object sender, EventArgs e) in '

**Comment by koculu** [comment] 2024-12-19 18:09
It seems you get the error, because you don't correctly dispose the disposables.
It is also recommended to create a maintainer that handles background compaction jobs.
Make sure you properly managed the life cycle of your ZoneTree instance.

Here is the working example code in VB.
```vb
Imports Tenray.ZoneTree
Imports Tenray.ZoneTree.Comparers
Imports Tenray.ZoneTree.Serializers
Public Class ZoneTreeProvider
    Public Function OpenDb(dataPath As String) As IZoneTree(Of String, Memory(Of Byte))
        Dim zoneTree = New ZoneTreeFactory(Of String, Memory(Of Byte))() _
            .SetComparer(New StringOrdinalComparerAscending()) _
            .SetDataDirectory(dataPath) _
            .SetKeySerializer(New Utf8StringSerializer()) _
            .OpenOrCreate()
        Return zoneTree
    End Function
End Class

Module Program
    Sub Main(args As String())
        Dim provider As New ZoneTreeProvider
        Using database As Tenray.ZoneTree.Core.ZoneTree(Of String, Memory(Of Byte)) = provider.OpenDb("data\testdb5")

            Using maintainer = database.CreateMaintainer()
                Dim Name As String = "name"
                Dim data As Byte()
                ReDim data(100) '
                data(5) = 10
                Dim memoryData As Memory(Of Byte) = New Memory(Of Byte)(data)
                Dim watch As New Stopwatch
                watch.Start()

                Dim opindex As Long
                For i As Integer = 0 To 1000000
                    database.TryAtomicAdd("kalle" & i, memoryData, opindex)
                Next

                watch.Stop()
                maintainer.WaitForBackgroundThreads()
            End Using
        End Using
    End Sub
End Module
```

**Comment by koculu** [comment] 2024-12-19 18:53
Your second question: No, there is no need to flush data to disk. Everything is automatically handled by ZoneTree.

**Comment by koculu** [comment] 2024-12-19 18:56
Closing the issue as "functions as designed".

**Closed by koculu** 2024-12-19 18:56 UTC
